name: MRC
version: 20.10.16

description: Runs Minecraft Robotics Competition matches.
author: Nicholas Bottone
website: https://www.bottone.io

main: io.bottone.mc.plugins.mrc.MRC
database: false
depend: [HolographicDisplays, WorldEdit]
softdepend: [Vault]
api-version: 1.15

commands:
  spectate:
    description: Enters MRC spectator mode.
    usage: /spectate
  pos:
    description: Selects a position to compete in.
    usage: /pos <position>
  class:
    description: Selects a class to compete in.
    usage: /class <class>