name: MRC
version: 20.11.12

description: Runs Minecraft Robotics Competition matches.
author: Nicholas Bottone
website: https://www.bottone.io

main: io.bottone.mc.plugins.mrc.MRC
database: false
depend: [HolographicDisplays, WorldEdit]
softdepend: [Vault]
api-version: 1.15

commands:
  spectate:
    description: Enters MRC spectator mode.
    usage: /spectate
  pos:
    description: Selects a position to compete in.
    usage: /pos <position>
  class:
    description: Selects a class to compete in.
    usage: /class <class>
  reloadrecords:
    description: Reloads MRC world records.
    usage: /reloadrecords
    permission: mrc.fta
  records:
    description: See the MRC world records.
    usage: /records
  wr:
    description: See the MRC world records.
    usage: /wr
  pb:
    description: See your MRC personal best.
    usage: /pb
  personalbest:
    description: See your MRC personal best.
    usage: /personalbest