name: MRC
version: 20.8.4

description: Runs Minecraft Robotics Competition matches.
author: Nicholas Bottone
website: https://www.bottone.io

main: io.bottone.mc.plugins.mrc.MRC
database: false
depend: [HolographicDisplays, WorldEdit]
softdepend: [Vault]
api-version: 1.15

commands:
  spectate:
    description: Starts spectating the MRC match.
    usage: /spectate