name: MRC-Pits
version: 20.12.18-SNAPSHOT

description: Runs the Minecraft Robotics Competition event pits.
author: Nicholas Bottone
website: https://mc.bottone.io

main: io.bottone.mc.plugins.mrc.MRC
database: false
depend: [HolographicDisplays, WorldEdit]
softdepend: [Vault]
api-version: 1.15

commands:
  spectate:
    description: Enters MRC spectator mode.
    usage: /spectate
  pos:
    description: Selects a position to compete in.
    usage: /pos <position>
  class:
    description: Selects a class to compete in.
    usage: /class <class>
  teamchat:
    description: Sends a message privately to your alliance partners.
    usage: /teamchat <message>
    aliases: team, chat, tc
